trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'mernacr123321'
  IMAGE_NAME: 'simple-app'

steps:

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: 'acr-connection'
    repository: $(IMAGE_NAME)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: latest

- script: |
    kubectl rollout restart deployment simple-app
  displayName: Deploy to AKS