apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app-dev
  template:
    metadata:
      labels:
        app: simple-app-dev
    spec:
      containers:
      - name: simple-app
        image: pramodnewacr.azurecr.io/simple-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000

        volumeMounts:   # ✅ ADDED
        - mountPath: /data
          name: app-storage

        env:
        - name: PORT
          value: "4000"
        - name: ENV
          value: "DEV"

      volumes:   # ✅ ADDED
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-dev
spec:
  type: ClusterIP
  selector:
    app: simple-app-dev
  ports:
  - port: 80
    targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-prod
spec:
  replicas: 1   # ⚠️ CHANGED (IMPORTANT for PVC)
  selector:
    matchLabels:
      app: simple-app-prod
  template:
    metadata:
      labels:
        app: simple-app-prod
    spec:
      containers:
      - name: simple-app
        image: pramodnewacr.azurecr.io/simple-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000

        volumeMounts:   # ✅ ADDED
        - mountPath: /data
          name: app-storage

        env:
        - name: PORT
          value: "4000"
        - name: ENV
          value: "PROD"
        - name: DATABASE_URL
          value: ""

      volumes:   # ✅ ADDED
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-prod
spec:
  type: ClusterIP
  selector:
    app: simple-app-prod
  ports:
  - port: 80
    targetPort: 4000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-ingress
  annotations:
    appgw.ingress.kubernetes.io/backend-port: "4000"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "my-ssl-cer-new"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: pramodkumar.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app-prod
            port:
              number: 80
  - host: dev.pramodkumar.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app-dev
            port:
              number: 80