apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: mernacr123321.azurecr.io/simple-app
        imagePullPolicy: Always
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  type: LoadBalancer   # 🔥 UPDATED (IMPORTANT)
  selector:
    app: simple-app
  ports:
  - port: 80
    targetPort: 4000